### ISSUE TITLE
Please allow use of existing AppProjects if available

### ISSUE THREAD

**Issue by RickJWagner** [RoadieHQ/roadie-backstage-plugins#1500]
Feature Suggestion

Every time the backstage ArgoCD plugin is invoked it must create a new ArgoCD "AppProject".  

This goes against how many (most?) organizations build out their Argo CD architecture.  An "AppProject" often is used as a way to logically organize groups of Argo CD "Applications".  However, it is rare that all of these "Applications" are created at the exact same time.

The plugin should be able to take an existing "AppProject" name as a parameter and simply use this if it already exists, and only create a new "AppProject" if it doesn't.

Possible Implementation

N/A

Context

We'd like to be able to use the plugin, but not have a new AppProject every time it runs.

Thank you!

**Comment by pittar** [comment]
If this feature isn't created, is there a better way to be able to keep adding Applications to AppProjects, rather than having to create a new AppProject each time you invoke a GPT?

**Comment by Xantier** [comment]
@RickJWagner Would you be able to recommend an alternative approach to this?

**Comment by RickJWagner** [comment]
Hi @Xantier 
Thank you for asking.  Let me delegate the question to some friends that have much more experience in the area.
@pittar , @agiertli, can we think of any alternative approaches?  Thanks.

**Comment by pittar** [comment]
For one of the large-scale customers that I work with, this is a blocker to them adopting Backstage.  Since the Argo CD integration is a core requirement, the fact that each new Argo CD "Application" also requires a new "AppProject" makes this plugin unusable.

To explain further, they have an "AppProject" per project team.  When a project team needs to create a new "Application", it references the existing "AppProject".

This is a problem with the argocd plugin, since attempting to create a new "Application" that belongs to an existing "AppProject" throws an error.

Ideally, this plugin would have an additional flag - something along the lines of "useExistingAppProject" that would simply skip the AppProject creation step and allow an Application to reference and existing AppProject.

**Comment by Xantier** [comment]
Thanks @pittar,

Would you or Red Hat be able to introduce such functionality to this plugin? We currently don't have ArgoCD setup that would match that kind of workflow so it is a bit tricky to modify without a proper test environment.
