### ISSUE TITLE
Filter Activity Stream by Component

### ISSUE THREAD

**Issue by crivetechie** [RoadieHQ/roadie-backstage-plugins#183]
The current behaviour of the plugin is to provide a summary of the opened issues filtering by component (`jira/component`) and project (`jira/project-key`) as well as displaying the activity stream for the whole project.

Would it be possible to make it so that the "Activity stream" shows only the activity for the issues related to the Component identified by the annotation `jira/component` rather than displaying the activity for the whole project `jira/project-key` ?

**Comment by callmegar** [comment]
+1 on this, removing the activity stream is good in this situation, another option could be to add an Epic and pull only issues from a specific Epic into the activity stream

**Comment by ivangonzalezacuna** [comment]
I've been testing an option to filter the activity stream and I think I found a solution for it. 

In our company's JIRA instance we have a filter by `issue-key`, so I changed the issueTypeCounter to a paged request getting only the issue key and the issue type object to reduce the amount of data. Then I use a `.reduce()` to make the count as before and, finally, I store a list of issue-keys. That list will be used to fetch the stream instead of the project key:`streams=issue-key+IS+(list of issue keys)`. I also found out the confluence activities might be filtered out as well, at least for our case.

If you want to, I could create a pull request for that, I guess it's the only possible option to filter the activity stream right now, but only if your company has the `issue-key` filter available.
