### ISSUE TITLE
Support monorepos - Better filtering options for PRs

### ISSUE THREAD

**Issue by iain-b** [RoadieHQ/roadie-backstage-plugins#285]
Users with monorepos have given feedback that the pull requests plugin isn't that useful where they have a monorepo because the PR list is for the full repo which contains several projects. 

## Feature Suggestion

Allow some means of filtering out only PRs relevant to certain components.

## Possible Implementation

Use the search API to filter by label ? The label could be set via annotation (there is an action to automatically label based on path)

Searching by assignee might be of some use here if using Codeowners but it's quite likely that a given group might have more than one folder in the mono repo to be responsible for (hence we're back to the same issue). This apparch might be useful for user / group entities however.

## Context

labeler action: https://github.com/actions/labeler

**Comment by kunickiaj** [comment]
Would definitely like to see this as well. Similar to the homepage widget, customizing the PRs tab would be useful.
Since I don't think PRs are filterable by file path (which is in one of the entity annotations already) just having customization on the filter would be nice. For example `<entity name> in:title`
