### ISSUE TITLE
Cannot install scaffolder-backend-module-http-request in Backstage

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/roadie-backstage-plugins#350]
## Expected Behavior

Running `yarn install` should succeed.

## Current Behavior

I see this error: `error An unexpected error occurred: "expected workspace package to exist for \"@types/webpack\"".`

```
**cd packages/backend**
**yarn add @roadiehq/scaffolder-backend-module-http-request**
yarn add v1.22.1
[1/4] 🔍  Resolving packages...
warning Lockfile has incorrect entry for "ws@7.4.5". Ignoring it.
[2/4] 🚚  Fetching packages...
info esbuild-android-arm64@0.14.10: The platform "darwin" is incompatible with this module.
# [...]
**error An unexpected error occurred: "expected workspace package to exist for \"@types/webpack\"".**
info If you think this is a bug, please open a bug report with the information provided in yarn-error.log
```

Manually editing the `packages/backend/package.json` to add `@roadiehq/scaffolder-backend-module-http-request` and running `yarn install` works successfully.

## Steps to Reproduce

See above.

## Possible Solution

Possibly related to https://github.com/yarnpkg/yarn/issues/7807?

## Your Environment

I'm on an M1 Mac Air

```
yarn --version
1.22.1

node --version
v16.4.0
```

My backend package is:

```
{
  "name": "example-backend",
  "version": "0.2.59",
}
```

**Comment by dtuite** [comment]
@Xantier  I am still experiencing this problem. Here's my reproduction steps:

```
git clone git@github.com:RoadieHQ/backstage.git
cd backstage
yarn && yarn clean && yarn tsc && yarn build
cd packages/backend
yarn add @roadiehq/scaffolder-backend-module-http-request@latest
error An unexpected error occurred: "expected workspace package to exist for \"@types/webpack\"".
```

**Comment by dtuite** [comment]
Once again, manually adding the package works ok.

```json-diff
diff --git a/packages/backend/package.json b/packages/backend/package.json
index f20465978..3dd5e2a98 100644
--- a/packages/backend/package.json
+++ b/packages/backend/package.json
@@ -58,6 +58,7 @@
     "@backstage/plugin-todo-backend": "^0.1.17",
     "@gitbeaker/node": "^34.6.0",
     "@octokit/rest": "^18.5.3",
+    "@roadiehq/scaffolder-backend-module-http-request": "2.1.2",
     "azure-devops-node-api": "^11.0.1",
     "dockerode": "^3.3.1",
     "example-app": "^0.2.58",
```

```
cd ../..
yarn install
✨  Done in 146.57s
```

**Comment by Xantier** [comment]
This seems to be an issue related to later versions if `yarn` 1.x, which is deprecated. You can downgrade to a lower version which should work or upgrade to use yarn 2.

The following set of commands will work when adding the package (from the root of the project):
`find . -name 'node_modules' -type d -prune -print -exec rm -rf '{}' \;`
`yarn policies set-version 1.19.0`
`yarn && yarn tsc && yarn build`
`cd packages/backend`
`yarn add @roadiehq/scaffolder-backend-module-http-request`


Alternatively you can add the package using lerna since backend is a monorepo using lerna (from the root of the project):
`yarn lerna add --scope="example-backend" @roadiehq/scaffolder-backend-module-http-request`
