### ISSUE TITLE
Jira Plugin - Usage of Development Information

### ISSUE THREAD

**Issue by regicsolutions** [RoadieHQ/roadie-backstage-plugins#705]
## Feature Suggestion

The component field in Jira is not always used or enforced in issues making it difficult to make use of this plugin at scale. This suggestion is to make use of [Jira Development Data](https://developer.atlassian.com/cloud/jira/software/rest/api-group-development-information/) instead of relying on a Jira project key or component name.  

## Possible Implementation

This proposal does make the assumption that your backstage component name is the same as your repository name. With the repository name you can get pretty insightful data including project/issue key, commits, active branches, and pull request data. 

## Context

Get instant and full visibility into a backstage components activity in Jira without depending on a project key or component name.

**Comment by kissmikijr** [comment]
Thanks for raising this! Actually we are thinking about to start working towards a jira plugin 2.0 because we realized that the current implementation is the best. It is not the most useful plugin for tying these project informations to backstage components. 

This API looks interesting, it will be considered during the planning of the next gen of Jira plugin.
