### ISSUE TITLE
How to use OAuth access token for Jira plugin?

### ISSUE THREAD

**Issue by chuliang014** [RoadieHQ/roadie-backstage-plugins#95]
I've already create a OAuth access token, but seemed not work with plugin.

Could anyone use OAuth as well, but work?

**Comment by Xantier** [comment]
Hi @chuliang014,

We have taken the approach to provide a common auth for all users via the backend proxy using an API key, instead of OAuth for individual users. It could be a good addition to the plugin to use user specific tokens, but it is currently not supported. 

Would that be something you could have time to contribute to these plugins?

**Comment by chuliang014** [comment]
cause my project is in a hurry to go live, so I should not have time to contribute this at this moment.

**Comment by chuliang014** [comment]
> Hi @chuliang014,
> 
> We have taken the approach to provide a common auth for all users via the backend proxy using an API key, instead of OAuth for individual users. It could be a good addition to the plugin to use user specific tokens, but it is currently not supported.
> 
> Would that be something you could have time to contribute to these plugins?

cause my project is in a hurry to go live, so I should not have time to contribute this at this moment.

**Comment by martina-if** [comment]
I'll close this in favor of https://github.com/RoadieHQ/roadie-backstage-plugins/issues/184
