### ISSUE TITLE
Customize frequency of refresh interval for catalog-backend-module-okta plugin

### ISSUE THREAD

**Issue by EricaJ6** [RoadieHQ/roadie-backstage-plugins#971]
## Feature Suggestion

Support customization for refresh interval frequency, timeout, and delay time while pulling in data from Okta for users and groups.

## Possible Implementation

Update `fromConfig` to accept the TaskRunner scheduler as one of the configuration for `frequency`, `timeout`, and `initialDelay`. With this functionality, it can be used as below:

```
  const schedule = env.scheduler.createScheduledTaskRunner({
    frequency: { days: 1 },
    timeout: { minutes: 15 },
    initialDelay: { seconds: 3 },
  });

  const orgProvider = OktaOrgEntityProvider.fromConfig(env.config, {
    logger: env.logger,
    userNamingStrategy: 'strip-domain-email',
    groupNamingStrategy: 'kebab-case-name',
    schedule,
  });
```

## Context

While using this `catalog-backend-module-okta` plugin in our project, we would like to have the ability to set up the frequency for refresh interval. While the current design of `fromConfig` does not accept the TaskRunner scheduler. We're thinking to use the `setProcessingIntervalSeconds` from `CatalogBuilder`. However, with this configuration, it may affect other settings of the Catalog. It will be more convenient and handy if this `catalog-backend-module-okta` plugin can support the TaskRunner scheduler. We noticed that the LdapOrgEntityProvider is supporting this feature. For your reference, it is at https://backstage.io/docs/integrations/ldap/org/.

**Comment by kissmikijr** [comment]
Thank you for raising this. This is the common pattern that is in the main backstage/backstage repository. Most of the providers built the way you are suggesting and I think it makes sense to add it to this also. As a workaround, you can use the scheduler directly in the catalog.ts to schedule your provider.

```
    await env.scheduler.scheduleTask({
      id: <id>,
      fn: oktaProvider.run,
      frequency: Duration.fromObject({ minutes: 5 }),
      timeout: Duration.fromObject({ minutes: 10 }),
    });
```

**Comment by bbegw** [comment]
Thanks very much for the workaround suggestion @kissmikijr ! When we implemented your suggestion, we are seeing an error because it looks like the `connection` object inside the provider is not initialized. Have you seen this before and do you have any suggestions on how to resolve? Thank you!

`[1] 2023-05-04T17:58:21.654Z backstage info Task worker starting: OktaEntityProvider, {"version":2,"cadence":"PT59M","timeoutAfterDuration":"PT10M"} type=taskManager task=OktaEntityProvider
[1] 2023-05-04T17:58:21.660Z backstage error Not initialized type=taskManager task=OktaEntityProvider stack=Error: Not initialized
[1]     at TaskWorker.run [as fn] (/Users/zzz/git/nova/supernova/node_modules/@roadiehq/catalog-backend-module-okta/dist/index.cjs.js:428:13)
[1]     at TaskWorker.runOnce (/Users/zzz/git/nova/supernova/node_modules/@backstage/backend-tasks/dist/index.cjs.js:360:18)
[1]     at async /Users/zzz/git/nova/supernova/node_modules/@backstage/backend-tasks/dist/index.cjs.js:308:31
[`

**Comment by kissmikijr** [comment]
Make sure you put the schedule after you already built the builder.

```ts
  const { processingEngine } = await builder.build();

  await processingEngine.start();
  
  await env.scheduler.scheduleTask({
      id: <id>,
      fn: oktaProvider.run,
      frequency: Duration.fromObject({ minutes: 5 }),
      timeout: Duration.fromObject({ minutes: 10 }),
    });
    
  ```

**Comment by rohitkedari** [comment]
the 'Not initialized' error is still there for scheduled task even after adding scheduleTask statement after built the builder, it is happening due to 'this' context issue. Following worked for me, in case anyone facing same issue it may help.
`const { processingEngine } = await builder.build();

  await processingEngine.start();
  
  await env.scheduler.scheduleTask({
      id: <id>,
      fn: () => oktaProvider.run(),
      frequency: Duration.fromObject({ minutes: 5 }),
      timeout: Duration.fromObject({ minutes: 10 }),
    });`

**Comment by billabongrob** [comment]
I've tried this same implementation using both Duration and just `frequency: { hours: 3 }` and this still isn't working for me.  It appears that the Okta runner is occurring once hourly regardless of how it's being adjusted.
